services:
  backend:
    build: ./backend
    env_file:
      -  ./.env
    ports:
      - "8000:8000"
#  frontend:
#    build: ./frontend
#    ports:
#      - "3001:3000"
#    depends_on:
#      - backend
